networks:
  shared:
    external: true
    name: homechef-shared

services:
  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    environment:
      - NODE_ENV=development
      - KAFKA_BROKERS=homechef-kafka:29092
      - KAFKA_TOPIC=order-created
      - REDIS_HOST=homechef-redis
      - REDIS_PORT=6379
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_SECURE=false
    volumes:  
      - ./services/notification-service:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - shared

  semantic-search:
    build: ./services/semantic-search
    container_name: semantic-search
    ports:
      - "3000:3000" 
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - shared

  mongodb:
    image: mongo:6.0
    container_name: chat-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      # MONGO_INITDB_ROOT_USERNAME: admin 
      # MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: chats
    volumes:
      - mongodb_data:/data/db 
    networks:
      - shared

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025" 
    networks:
      - shared

volumes:
  mongodb_data: 
    driver: local
